//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAppleShoppingStore.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverOrder
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Status { get; set; }
        public string DeliverVia { get; set; }
    
        public virtual Order Order { get; set; }
    }

    public enum Status : int
    {
        Ordered,
        Canceled,
        InProgress,
        Delivered
    }

    public enum DeliverVia : int
    {
        Courier,
        PostMail,
        Store
    }
}
